mailfriend/urls.py
from django.conf.urls.defaults import *

from mailfriend.views import *

urlpatterns = patterns('',
  url(
    regex   = '^(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
    view    = mail_item_to_friend_form,
    name    = 'mail_item_to_friend_form',
  ),
  url(
    regex   = '^send/$',
    view    = mail_item_to_friend_send,
    name    = 'mail_item_to_friend_send',
  ),
)

mailfriend/models.py
import datetime

from django.db import models
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User

class MailedItem(models.Model):
  content_type                    = models.ForeignKey(ContentType)
  object_id                       = models.IntegerField()
  content_object                  = generic.GenericForeignKey()
  mailed_by                       = models.ForeignKey(User)
  mailed_to                       = models.EmailField()
  user_email_as_from              = models.BooleanField(default=False)
  send_to_user_also               = models.BooleanField(default=False)
  date_mailed                     = models.DateTimeField(default=datetime.datetime.now, editable=False)

  def __unicode__(self):
    return "%s: To %s, from %s" % (unicode(self.content_object), self.mailed_to, unicode(self.mailed_by))

mailfriend/forms.py
from django import forms

from mailfriend.models import MailedItem

class MailedItemForm(forms.ModelForm):
  class Meta:
    model = MailedItem
    exclude = ('mailed_by','date_mailed')

mailfriend/views.py
import datetime

from django.shortcuts import render_to_response
from django.http import Http404
from django.contrib.sites.models import Site
from django.contrib.contenttypes.models import ContentType
from django.template import RequestContext, loader, Context
from django.conf import settings
from django.contrib.auth.decorators import login_required

# If djano-mailer (http://code.google.com/p/django-mailer/) is available,
# favor it. Otherwise, just use django.core.mail. Thanks to brosner for the
# suggestion (you can also blame him if this doesn't work. Joking. Sort of.)
try:
  from mailer import send_mail
except ImportError:
  from django.core.mail import send_mail

from mailfriend.models import *
from mailfriend.forms import *

@login_required
def mail_item_to_friend_form(request, content_type_id, object_id):
  content_type = ContentType.objects.get(pk=content_type_id)
  try:
    obj = content_type.get_object_for_this_type(pk=object_id)
    obj_url = obj.get_absolute_url()
  except ObjectDoesNotExist:
    raise Http404, "Invalid -- the object ID was invalid"
  form = MailedItemForm()
  context = {
    'content_type': content_type,
    'form': form,
    'object': obj,
  }
  return render_to_response('mailfriend/form.html', context, context_instance=RequestContext(request))
  

@login_required
def mail_item_to_friend_send(request):
  if not request.POST:
    raise Http404, "Only POSTs are allowed"
  content_type = ContentType.objects.get(pk=int(request.POST['content_type']))
  try:
    obj = content_type.get_object_for_this_type(pk=int(request.POST['object_id']))
    obj_url = obj.get_absolute_url()
  except ObjectDoesNotExist:
    raise Http404, "The send to friend form had an invalid 'target' parameter -- the object ID was invalid"
  site              = Site.objects.get_current()
  site_url          = 'http://%s/' % site.domain
  url_to_mail       = 'http://%s%s' % (site.domain, obj_url)
  sending_user      = request.user
  subject           = "You have received a link"
  message_template  = loader.get_template('mailfriend/email_message.txt')
  message_context   = Context({ 
      'site': site,
      'site_url': site_url,
      'object': obj,
      'url_to_mail': url_to_mail,
      'sending_user': sending_user,
  })
  message           = message_template.render(message_context)
  recipeient_list   = [request.POST['mailed_to']]
  if request.POST.has_key('send_to_user_also'):
    recipeient_list.append(request.user.email)
  if request.POST.has_key('user_email_as_from'):
    from_address    = request.user.email
  else:
    from_address    = settings.DEFAULT_FROM_EMAIL
  send_mail(subject, message, from_address, recipeient_list, fail_silently=False)
  mailed_item       = MailedItem(date_mailed=datetime.datetime.now(), mailed_by=sending_user)
  form              = MailedItemForm(request.POST, instance=mailed_item)
  new_mailed_item   = form.save()
  context = Context({ 'object': obj })
  return render_to_response('mailfriend/sent.html', context, context_instance=RequestContext(request))
  
  
  

mailfriend/templates/form.html
{% extends "base.html" %}

{% block content %}
  <h2>E-mail to a friend</h2>
  <p>To e-mail <a href="{{ object.get_absolute_url }}">{{ object }}</a> to a friend, fill out the short form below. Note that if you select "Use my e-mail address as from address", your e-mail address will be visible to your friend, and they will be able to reply to you. If you do not select this box, your friend will receive an e-mail from an address that does not accept replies and they will <em>not</em> be able to see your e-mail address.</p>
  <form action="{% url mail_item_to_friend_send %}" method="post">
    <input type="hidden" id="id_content_type" name="content_type" value="{{ content_type.id }}">
    <input type="hidden" id="id_object_id" name="object_id" value="{{ object.id }}">
    <label for="id_mailed_to">Mail to:</label> {{ form.mailed_to }}
    <label for="id_user_email_as_from">Use my e-mail address as from address:</label> {{ form.user_email_as_from }}
    <label for="id_send_to_user_also">Send myself a copy of this e-mail:</label> {{ form.send_to_user_also }}
    <input type="submit" value="submit" />
  </form>
{% endblock %}

mailfriend/templates/sent.html
{% extends "base.html" %}

{% block content %}
  <h2>Message sent!</h2>
  <p>You probably want to <a href="{{ object.get_absolute_url }}">go back to {% firstof object.title object.name object %}</a>.</p>
{% endblock %}